trigger:
  batch: true
  branches:
    include:
      - dev
  tags: 
    include: 
    - dev.build.*

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: academy-dev

steps:
  - task: NodeTool@0
    inputs:
      versionSource: 'spec'
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - task: Npm@1
    displayName: "Clean Install npm packages"
    inputs:
      command: "ci"

  - task: Npm@1
    displayName: "Database setup"
    inputs: 
      command: "custom"
      customCommand: "run dev:db:setup"

  - task: Npm@1
    displayName: "Build and prune"
    inputs:
      command: "custom"
      customCommand: "run build:clean"

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true

  - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    artifact: Popscle-Dev-Build
    displayName: 'Publish Build'
  
  - task: AzureRmWebAppDeployment@4
    displayName: 'Deploy Azure App Service'
    inputs:
      azureSubscription: '$(ConnectedServiceName)'
      appType: '$(WebAppKind)'
      WebAppName: '$(WebAppName)'
      packageForLinux: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      StartupCommand: 'npm run start-prod'


